export const AUTH_SET_TOKEN = "AUTH_SET_TOKEN";
export const AUTH_REMOVE_TOKEN = "AUTH_REMOVE_TOKEN";

// Destination
export const SET_DESTINATIONS = "SET_DESTINATIONS";
export const DELETE_DESTINATION = "DELETE_DESTINATION";
export const SET_SELECTED_DESTINATION = "SET_SELECTED_DESTINATION";
// export const
